version: '3.9'
services:
  database:
    image: postgres:15.8
    container_name: custom_postgres
    environment:
      POSTGRES_USER: it
      POSTGRES_PASSWORD: 0000
      POSTGRES_DB: nlb
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: custom_grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=it
      - GF_SECURITY_ADMIN_PASSWORD=0000
      - GF_AUTH_ANONYMOUS_ENABLED=true
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana.ini:/etc/grafana/grafana.ini
    restart: always

  mongodb:
    image: mongo:latest
    container_name: custom_mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=it
      - MONGO_INITDB_ROOT_PASSWORD=0000
    volumes:
      - mongo_data:/data/db
    restart: always

  mongo-express:
    image: mongo-express
    container_name: custom_mongo_express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=custom_mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ADMINUSERNAME=it
      - ME_CONFIG_MONGODB_ADMINPASSWORD=0000
    restart: always

volumes:
  db_data:
  grafana_data:
  mongo_data:
