mail.host=smtp.gmail.com
mail.port=587
mail.username=teummeireprj@gmail.com
mail.password=xwuhcgdzxrgebfwx
mail.protocol=smtp
mail.auth=true
mail.starttls.enable=true
mail.starttls.required=true
mail.ssl.trust=smtp.gmail.com
mail.debug=true
